### ISSUE TITLE
installer script isn't fail safe

### ISSUE THREAD

**Issue by buixor** [crowdsecurity/cs-standalone-php-bouncer#12]
- the installation doesn't fail if composer is missing
 - the gregwar/captha module requires `gd`, but the script won't complain if dependency cannot be met
 - maxmind/web-service-common v0.8.1 requires ext-curl * -> the requested PHP extension curl is missing from your system.
 -

**Comment by julienloizelet** [comment]
Closing because the new version 1.0.0 is a total redesign.
Thanks
