### ISSUE TITLE
IP got blocked by crowdsec instead of captcha

### ISSUE THREAD

**Issue by gdudas** [crowdsecurity/cs-standalone-php-bouncer#2]
Hi,

I have installed crowdsec (version: v1.2.0-0ecfe7568790a15791011da27eb24e96e7d4a39f) and crowdsec-firewall-bouncer, and the IP got blocked by crowdsec instead of captcha. If crowdsec-firewall-bouncer disabled, captcha does not show.

What can be wrong?

**Comment by JoshWho** [comment]
change the setting to flex_boucing

**Comment by julienloizelet** [comment]
Closing because the new version 1.0.0 is a total redesign.
Thanks
